### ISSUE TITLE
bulk_write support

### ISSUE THREAD

**Issue by dbanty** [cymoo/monom#1]
Hey there! I'm in the market for a MongoDB ODM-type library, ideally one with type annotations (like this one!). One feature I definitely need that almost no libraries seem to support today is the ability to bulk write changes for multiple records.

Meaning, I have some number N records which all are getting modified. They _are not_ all getting the same modifications, they have unique changes. I want to submit the changes to the database for all the records, but want to do it in a single round trip using [bulk_write](https://api.mongodb.com/python/current/api/pymongo/collection.html#pymongo.collection.Collection.bulk_write) to reduce overhead.

Is there already a way to do this with monom, or would you accept a contribution to add such a feature?

Thanks!

Another easier, smaller question (which I'll just put here so you don't have to look at two issues): would you add a PEP-561 py.typed file so that mypy will know to look for type annotations? [info on mypy](https://mypy.readthedocs.io/en/stable/installed_packages.html?highlight=py.typed#making-pep-561-compatible-packages).

**Comment by cymoo** [comment]
Sorry for such long time before I saw this issue:) 
I had the plan to add `bulk_write`, but delayed it for some reason.
Your PR is welcomed, and it will be nicer if you could add some test cases for the feature.

**Comment by dbanty** [comment]
Of course, not a problem. I wanted to make sure it was a feature you agreed with and have you look at my approach before I wrote out tests for it.  The way it's set up, it would work something like this:

```
result = MyModel.save_multiple([first_one, second_one])
```

Where:
1. `MyModel` is the user-defined model class
2. `first_one` and `second_one` are instances of `MyModel`
2. `result` is a [BulkWriteResult](https://api.mongodb.com/python/current/api/pymongo/results.html#pymongo.results.BulkWriteResult) so you can get inserted IDs, counts of things changed, etc.

If this API looks good to you I'll go ahead and make some tests for it. Do you also want me to write any docs about it? Looks like everything is just in README, I could mention in there somewhere.

**Comment by cymoo** [comment]
This API is nice!
It will be very helpful if you could help write docs for it. The README is a bit terrible:(
